POC: load project into editor when app starts
MacareuxDigital/takamatsu-scratch pull request #2
Opened 2024-10-03 08:29 UTC by aquino-luane

Consumes a mock api that returns a .sb3 files, then set the response to the store

2024-10-16 23:19 UTC, hissy requested changes
It works as expected; thank you!
Next step: Let's enable it to define project ID.

I've uploaded a new json file to update your mock API.
https://drive.google.com/open?id=1M2RjMB8ku5_JeIA-zLdvhtsDLKDGzMvt&usp=drive_fs

It accepts a path parameter to set a project ID.
If the given project ID is correct, the API returns the sb3 file.
If it is not correct, the API returns a 404 response.

It's better if we can use React Router.
https://reactrouter.com/en/main

Browser Router (e.g. `http://127.0.0.1:8080/projects/1` ) looks beautiful, but we can also use HashRouter (e.g. `http://127.0.0.1:8080/#/projects/1`).

You can refer to how scratch-www repository does.
https://github.com/scratchfoundation/scratch-www/blob/develop/src/views/preview/project-view.jsx

I have a plan to update the mock API to accept user authenticate token, but that is a further step.

2024-10-17 09:31 UTC, aquino-luane commented
@hissy just to confirm how this part would work:

Will the backend return something like a projectId in the JWT Token? I ask this to confirm if the flow will be like this:
user opens the app, then backend returns projectId in the payload of the JWT. 
If projectId is valid than the frontend make a request to get the project files http://127.0.0.1:8080/projects/1
but if is not valid, then don't make a request, just shows default project

2024-10-18 07:53 UTC, hissy commented
@aquino-luane 

There's a project list on the Concrete site. If the user clicks one of them, they'll go to the /projects/1

2024-10-22 09:23 UTC, aquino-luane commented
@hissy 
I committed the solution using hash router, could you review please?

About using router dom, I investigated more but was not able to figure out what is the cause. I think we can return to this issue later, as an improvement.
I also posted this question on two places, maybe someone else already knows the answer. https://stackoverflow.com/questions/79113275/is-it-possible-to-use-react-router-dom-in-scratch-gui-if-so-how-can-i-do-it and https://github.com/scratchfoundation/scratch-gui/issues/9707

2024-10-22 12:00 UTC, hissy commented
@aquino-luane 

We need to get project ID from URL.

2024-10-28 05:27 UTC, aquino-luane commented
> @aquino-luane
> 
> We need to get project ID from URL.

@hissy 
For the project I removed the mock to consume from redux https://github.com/MacareuxDigital/takamatsu-scratch/pull/2/commits/7c771fd4faef28072f6e3152743483cde59fb05b

I am still setting the hash in the code below, because I am not sure where it will come from. Should I also remove it?
![image](https://github.com/user-attachments/assets/dc1ff485-680c-4630-94ab-9c1242e8d3ba)

2024-10-28 05:37 UTC, aquino-luane commented
> We need to get project ID from URL.

Now I will try to setProjectId from the url

2024-10-28 07:00 UTC, hissy commented
@aquino-luane 

> I am still setting the hash in the code below, because I am not sure where it will come from.

It'll come from url.

2024-10-28 07:22 UTC, aquino-luane commented
> @aquino-luane
> 
> > I am still setting the hash in the code below, because I am not sure where it will come from.
> 
> It'll come from url.

@hissy so is it ok to keep this way (with the code setting the hash) until we integrate with cms? then we remove it

2024-10-29 07:03 UTC, aquino-luane commented
@hissy 
About the "Save Now" functionality, I made this changes and I seems to be working, to make a PUT request https://github.com/MacareuxDigital/takamatsu-scratch/pull/2/commits/abbfbda9e66535ffa7d7a42471f8e347954e1bb7

Also I checked about the autosave, and it seems to be working as it is. Each 2 minutes, if there is some change in the project, the request to the API is made. I tested it by adding some block, then after 2 min the request was made to the API. The code that makes the request is in the file `save-project-to-server.js`

2024-12-25 03:44 UTC, hissy requested changes
@aquino-luane 

Please update these changes:

* When creating a new project, post request to `/md/api/projects`
* When getting an existing project, get it from `/md/api/projects/{id}`
* When updating a project, post request to `/md/api/projects/{id}`
* Please always add JWT token in the header

2025-01-07 02:34 UTC, aquino-luane commented
> * Can you append a title of the project coming from `ProjectTitleInput` component?

For append you mean to send project title in the payload of an API request?

2025-01-07 03:37 UTC, hissy commented
@aquino-luane 

Yes. Please check the doc. The API accepts title (and optionally description) of projects

2025-03-10 01:56 UTC, closed without merging

2025-03-10 01:56 UTC, aquino-luane commented
Closing this PR as it is already in production