POC: add a sprite
MacareuxDigital/takamatsu-scratch pull request #4
Opened 2024-10-15 02:34 UTC by aquino-luane

## What this PR does?
Adds a sprite to library. Reference: https://gist.github.com/summerscar/586b88772c598efdbfecffa3c1212b79

## How to setup API mock?
We are using [Mockoon](https://mockoon.com/)  for API mock
Here are the files you need to set the mock API:
- `route-get-image.json`
- `60f720956ab1840431dcf0616ce98f14.svg`

Link to drive: https://drive.google.com/drive/folders/1ASWqP-JZXjmFqD_akaFnZ5IdqY4hKGRQ

To import the route to Mockoon, you copy the contents of the json file, then in Mockoon you select from the menu Routes>Add routes from clipboard
https://mockoon.com/docs/latest/mockoon-data-files/environment-clipboard-copy/#create-a-new-route-from-clipboards-data

After you import the route, you need to update the file path to point to the image you downloaded:
![image](https://github.com/user-attachments/assets/7d9dec1f-d1cb-46c0-9929-27679aeed7e1)

2024-10-17 03:15 UTC, hissy requested changes
Thank you very much.

Could you find the difference between costumes and sprites? Must we create both json files?

Also, can you update this PR to get json data from a mock API?
If you can, we can create a sprites database on the Concrete CMS side.

2024-10-22 06:06 UTC, aquino-luane commented
> Could you find the difference between costumes and sprites?

It is a good question 😄. The difference is small:
- if you are in the "Costumes" tab and select a costume you can stay in the same place, but if you select a sprite you go to "Code" tab
![image](https://github.com/user-attachments/assets/e6341732-f434-4ccd-b566-d7ecfa9764b7)
- costumes.json is what is shown in here:
![image](https://github.com/user-attachments/assets/7ad5dca7-f6a0-4c9d-9800-9699c7c1b23a)
- you can keep a list of customized sprites

> Must we create both json files?

sprites.json is needed. If we don't need the functionality to choose costumes then we don't need to create the costumes.json file

@hissy

2024-10-22 06:39 UTC, aquino-luane commented
> Also, can you update this PR to get json data from a mock API?
> If you can, we can create a sprites database on the Concrete CMS side.

@hissy do you mean to an API to return sprites.json? 
would we still download the sprite by requesting it by its md5 id like `http://localhost:3000/image/${asset.assetId}.${asset.dataFormat}` ?

2024-10-22 06:51 UTC, hissy commented
@aquino-luane 

> do you mean an API to return sprites.json?

Yes.

> would we still download the sprite by requesting it by its md5 id like http://localhost:3000/image/${asset.assetId}.${asset.dataFormat} ?

Yes.

Please check this sequence diagram, this is what I thought about loading sprites

https://cacoo.com/diagrams/nfYGhe7SZMAEv6sh/699AB

2024-10-23 02:50 UTC, aquino-luane commented
@hissy 
It seems to have no way to download the json and save to a specific location, because security reasons the file download can only be save into the downloads folder https://spin.atomicobject.com/create-export-react-frontend

The other way would be to save the json in redux. As it might be a big file, I am not sure if is good way here what do you think?

Will there be frequent update in the sprites and costumes? is it an option to keep the file locally without the request to server?

2024-10-23 03:27 UTC, hissy commented
@aquino-luane 

> The other way would be to save the json in redux. As it might be a big file, I am not sure if is good way, what do you think?

I think there's no problem. sprites.json is not small, but the same size will be removed from the built JS file.

> Will there be frequent update in the sprites and costumes? is it an option to keep the file locally without the request to server?

If API returns json data with cache-control header, your browser will keep it locally.

2024-10-23 08:06 UTC, aquino-luane commented
@hissy I committed the code to get json from API, could you review please?

Also uploaded the routes and files to drive:
route-get-sprites.json
route-get-costumes.json
costumes.json
sprites.json

2024-10-23 08:11 UTC, hissy commented
@aquino-luane 

Thanks, it looks fine for now. Let's wait for the API doc.

2024-12-25 03:57 UTC, hissy requested changes
Please change to get from the APIs instead of mock APIs.
Please check the design doc.
https://docs.google.com/document/d/1m8f_VfWhc2BbnyFnzLbr4iE4WsF2NjJ-uiD8b1_P6wY/edit?usp=sharing

2025-01-21 08:07 UTC, aquino-luane commented on src/containers/library-item.jsx
> +            `http://localhost:3000/image/${iconMd5}` :
@biplobice @hissy 
Is there an API endpoint that I can get an individual sprite by passing its MD5 value?

It seems that this is needed, because if I don't nothing shows in this screen (first image). Although if I select any sprite like "Andie" it will show in the editor (second image)... 
Image 1:
![image](https://github.com/user-attachments/assets/b39ec6a6-7133-4a72-b663-3bae1a5aa59e)
Image 2:
![image](https://github.com/user-attachments/assets/4c07bb7f-4abb-4d10-876b-cb76467b5003)

2025-01-21 08:39 UTC, biplobice commented on src/containers/library-item.jsx
> +            `http://localhost:3000/image/${iconMd5}` :
@aquino-luane 
Cc: @SashaMcr 
Yes, there is. The `/md/api/assets` is for that purpose.

2025-01-21 09:12 UTC, aquino-luane commented on src/containers/library-item.jsx
> +            `http://localhost:3000/image/${iconMd5}` :
Thank you!

2025-03-04 10:06 UTC, merged

2025-03-04 10:07 UTC, hissy commented
@aquino-luane 

Thanks. Let's apply to the production and try to test it