POC: manually set language translation to "choose an extension" modal title
MacareuxDigital/takamatsu-scratch pull request #7
Opened 2024-12-13 07:12 UTC by aquino-luane

`scratch-l10n` uses [transifex](https://www.transifex.com/) for translation. To use this service needs an API key, is not a free service.

So in this POC I manually get text translation based on locale. It only works for japanese and english, so for example If the user locale is of China, the modal title will default to english.

2024-12-13 07:26 UTC, hissy requested changes
@aquino-luane It looks great!
But it's better if we can capsulize the feature to get translated messages from english instead of working with json directly.

2024-12-13 07:37 UTC, aquino-luane commented
> @aquino-luane It looks great! But it's better if we can capsulize the feature to get translated messages from english instead of working with json directly.

Ok! I will think of other way.

Is there some security risk or other when working with json this way?

2024-12-13 08:39 UTC, hissy commented
@aquino-luane 

Not a security issue, just maintainability.

2024-12-13 10:05 UTC, aquino-luane commented
@hissy Maybe use [custom hook](https://react.dev/learn/reusing-logic-with-custom-hooks), what do you think?

The Hook would return an object with strings based on the locale. E.g.:

// useTextTranslations is the custom hook that return an object with translations in english or japanese, depending on locale
const messages = useTextTranslations()

// if locale is ja, custom hook returns:
messages: {
 chooseExtensionModalTitle: "プロジェクトのオプション拡張機能",
 someOtherText: "こんにちは",
 ...
}

<p>{messages.chooseExtensionModalTitle}</p>

2024-12-16 06:01 UTC, hissy commented
@aquino-luane 

Sounds nice

2024-12-17 05:32 UTC, aquino-luane commented
@hissy I refactored code to use HOC that return translated messages. Could you review please?

I was not able to use custom hooks, because to access Redux store in function components it requires the hook useSelector. But this hook is only available in react-redux from v7.1.0. I tried updating this package from v5, but it broke the application.

2024-12-25 02:49 UTC, hissy approved these changes

2024-12-25 02:49 UTC, merged

2024-12-25 02:51 UTC, hissy commented
@aquino-luane Thank you, it works as expected